#ifndef SRC_CUDALIBRARYTEST_GPUDEVICEPROPERTIES_HH_
#define SRC_CUDALIBRARYTEST_GPUDEVICEPROPERTIES_HH_

namespace MonteRay {

int getNumberOfGPUS(void);

}



#endif /* SRC_CUDALIBRARYTEST_GPUDEVICEPROPERTIES_HH_ */
